server:
  error:
    include-stacktrace: on_param
    include-message: always
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/person_finances?useSSL=false&createDatabaseIfNotExist=true
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
